### ISSUE TITLE
Add website link of text wizard to description

### ISSUE THREAD

**Issue by Sahilopl** [ADITYAVOFFICIAL/Text_Wizard#1]

**Comment by ADITYAVOFFICIAL** [comment]
it is already added

**Comment by ADITYAVOFFICIAL** [comment]
<img width="323" alt="Screenshot 2023-10-16 at 11 55 39 PM" src="https://github.com/ADITYAVOFFICIAL/Text_Wizard/assets/73814945/40543cc2-fc42-4675-9006-818897ea4404">
